# Generated by Django 5.2.5 on 2025-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meta_data',
            field=models.ManyToManyField(blank=True, related_name='course_metas', to='meta.metadata'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='meta_data',
            field=models.ManyToManyField(blank=True, related_name='enrollment_metas', to='meta.metadata'),
        ),
    ]
