# Generated by Django 5.2.5 on 2025-08-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='key',
            field=models.CharField(db_index=True, max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='metadata',
            unique_together={('key', 'value')},
        ),
    ]
