# Generated by Django 5.2.5 on 2025-08-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0002_alter_metadata_key_alter_metadata_unique_together"),
        ("user", "0002_alter_instructor_meta_data_alter_student_meta_data"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="StudentMetaData",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        # ('added_at', models.DateTimeField(auto_now_add=True)),
                        # ('is_filter', models.BooleanField(default=False)),
                        (
                            "metadata",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="meta.metadata",
                            ),
                        ),
                        (
                            "student",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="user.student",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "user_student_meta_data",
                        "unique_together": {("student", "metadata")},
                    },
                ),
            ]
        )
    ]
