# Generated by Django 5.2.5 on 2025-08-30 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0003_studentmetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmetadata",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentmetadata",
            name="is_filter",
            field=models.BooleanField(default=False),
        ),
    ]
