# Generated by Django 5.2.5 on 2025-08-30 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0005_remove_studentmetadata_is_filter_and_more'),
        ('user', '0003_alter_student_meta_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmetadata',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_metadata', to='meta.metadata'),
        ),
        migrations.AlterField(
            model_name='studentmetadata',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_metadata', to='user.student'),
        ),
    ]
