# Generated by Django 5.2.5 on 2025-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='meta_data',
            field=models.ManyToManyField(blank=True, related_name='instructor_metas', to='meta.metadata'),
        ),
        migrations.AlterField(
            model_name='student',
            name='meta_data',
            field=models.ManyToManyField(blank=True, related_name='student_metas', to='meta.metadata'),
        ),
    ]
