# Generated by Django 5.2.5 on 2025-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta", "0003_studentmetadata"),
        ("user", "0002_alter_instructor_meta_data_alter_student_meta_data"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="student",
                    name="meta_data",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="student_metas",
                        through="meta.StudentMetaData",
                        to="meta.metadata",
                    ),
                ),
            ]
        )
    ]
