# Generated by Django 5.2.5 on 2025-08-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_meta_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id']},
        ),
    ]
